baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Guillaume Lamps'
theme = 'iutdelens'

[[menu.main]]
    name = "À propos"
    url = "/a-propos-de"
[[menu.main]]
    name = "Projet"
    url = "/projet"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/VotreCompteGithub"
    pre = "<i class='fab fa-github'></i>"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
    name = "À propos"
    url = "/a-propos-de"

[params]
    author = "Guillaume Lamps"
    authorImage = "/images/nounours_ce-pédo_adoré.jpg"

paginate = 6

[[menu.main]]
    name = "Catégories"
    url = "/categories"